### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by tpmccallum** [second-state/wasmedge-extensions#3]
Hi
When attempting to update wasmedge-extensions to the latest version the following issue is occurring.

Line 377 of install.sh [1] is trying to download the following URL which does not exist.

https://github.com/second-state/WasmEdge-tensorflow/releases/download/0.9.0~rc.1/WasmEdge-tensorflow-0.9.0~rc.1-manylinux2014_x86_64.tar.gz

[1] https://github.com/WasmEdge/WasmEdge/blob/master/utils/install.sh#L377

**Comment by tpmccallum** [comment]
This is caused by an issue with tilde `~` vs dash  `-`

For example, the following release (where I replace the `~` with `-`) does exist.

https://github.com/second-state/WasmEdge-tensorflow/releases/download/0.9.0-rc.1/WasmEdge-tensorflow-0.9.0-rc.1-manylinux2014_x86_64.tar.gz

**Comment by tpmccallum** [comment]
You will notice that the `pre-install.sh` script [1] in the wasmedge-extensions/scripts directory actually uses a static version of the `install.sh` which does this conversion where the `-` is replaced with `~`

[1] https://github.com/second-state/wasmedge-extensions/blob/master/scripts/preinstall.sh#L8

**Comment by hydai** [comment]
Also, we have a working PR #4 to fix this issue.
