### ISSUE TITLE
Error when running FaaS 

### ISSUE THREAD

**Issue by tpmccallum** [second-state/wasmedge-extensions#7]
Hi 
I get the following error when running the face detection example on the FaaS.

https://www.secondstate.io/articles/faas-face-detection/

Interestingly it seems to fail after the Tensorflow detection and image modification have already taken place.

The FaaS is running the latest version of wasmedge-extensions (0.9.0) and other FaaS functions like hello world etc. seem to be working ok.

Any ideas?
Thanks

```
Parsed results in ... 528.026213ms
Drawing box: 30 results ...
Drawn on image in ... 572.980186ms
Success!

#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7ffd625c0050
 1: 0xaf8b71  [node]
 2: 0x1b04234 V8_Fatal(char const*, ...) [node]
 3: 0xf64ee9 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xca3028 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0xc1f96b void node::crypto::Decode<node::crypto::Hash>(v8::FunctionCallbackInfo<v8::Value> const&, void (*)(node::crypto::Hash*, v8::FunctionCallbackInfo<v8::Value> const&, char const*, unsigned long)) [node]
 6: 0xce224b  [node]
 7: 0xce37fc  [node]
 8: 0xce3e76 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
 9: 0x15046d9  [node]
Illegal instruction (core dumped)
```

**Comment by juntao** [comment]
Did you compile the Wasm file with Rust 1.50 or below?

**Comment by juntao** [comment]
I think we need to move away from `wasm-bindgen` and use the new `wasmedge-bindgen` instead. 

https://wasmedge.org/book/en/embed/go/function.html

https://wasmedge.org/book/en/embed/go/tensorflow.html

**Comment by tpmccallum** [comment]
Yes, Rust 1.5 was used to create the Wasm

It turns out that this error was caused by the version of NodeJs on the FaaS being too old (via package manager). I installed latest version of NodeJs, restarted the FaaS and the error went away.

I am interested in using wasmedge-bindgen also, so I will look into that soon.

Thanks :)
